name: Interact with AWS
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment (dev, staging, production)'
        options:
          - dev
          - staging
          - production
        default: "dev"
        required: true
      commitHash:
        description: 'Commit hash to checkout'
        required: true

jobs:
  test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
          with:
              ref: ${{ inputs.commit }}

        - name: List
          run: ls -al
