name: CI | Python
on:
  push:
    branches:
      - '*'
#     paths:
#       - './src/python/**'

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        run: echo "Checkout"
        
      - name: Set up Python
        run: echo "Setup Python"
        
      - name: Install dependencies
        run: echo "Install Dependencies"      

      - name: Test
        run: echo "make test"

  build:
    name: "Build"
    if: github.ref == 'refs/heads/main' || contains(github.event.head_commit.message, '--deploy')
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Build & Upload Artifact
        run: | 
          echo "Build & Upload artifact"

  deploy-staging:
    name: "Deploy | Staging"
    environment: Staging
    if: github.ref == 'refs/heads/main' || contains(github.event.head_commit.message, '--deploy')
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy To Staging
        run: | 
          echo "Deploy To Staging using $AWS_AK and $AWS_SK"
        env:
          AWS_AK: ${{ vars.AWS_AK }}
          AWS_SK: ${{ vars.AWS_SK }}
