name: TI - Ansible Mongodb Replicaset

on:
  workflow_dispatch:

jobs:
  infra:
    uses: rajalokan/learn-gh-actions/blob/main/.github/workflows/common.yaml@main
    secrets:
      password: rajalokan
