name: Deploy Job
run-name: Deploy to ${{ inputs.environment }} by @${{ github.actor }}

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      tag_name:
        required: false
        type: string
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: "The target environment for deployment"
        options:
          - dev
          - staging
          - test
          # - production
        default: "dev"
      tag_name:
        required: true
        type: string      
        default: "1234"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy New              
        env:
          VARS: ${{ toJSON(vars) }}
        run: |
          echo $VARS
          echo "Deploying ${{ inputs.tag_name }} to ${{ inputs.environment }}"
