name: Run Migration Analyzer

on:
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    # env:
    #   GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
