name: Multiorg Script Runner

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      script-name:
        description: Script to execute from the scripts directory.
        required: true
        type: choice
        options:
          - list-repo.sh
      org-names:
        description: Comma separated list of organization names.
        required: false

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      org-matrix: ${{ steps.format.outputs.org-matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate installation token
        if: ${{ github.event.inputs['org-names'] == 'ORG_ALL' }}
        run: |
          echo "Fetching installation token"

      - name: Prepare organization matrix
        id: format
        env:
          ORG_NAMES: ${{ inputs.org-names }}
          INSTALLATION_TOKEN: ${{ secrets.INSTALLATION_TOKEN }}
        run: python .github/scripts/prepare_org_matrix.py

  run-script:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        org: ${{ fromJson(needs.prepare.outputs.org-matrix) }}
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run selected script
        env:
          DEFAULT_SCRIPT_NAME: list-repo.sh
        run: |
          bash "./.github/scripts/${{ env.DEFAULT_SCRIPT_NAME }}" "${{ matrix.org }}"
