name: Run Every 5 Minutes

on:
  workflow_dispatch:
  schedule:
    # This cron expression runs the workflow every hour
    - cron: '*/6 * * * *'

jobs:
  deploy:
    uses: ./.github/workflows/example-deploy.yml
    with:
      environment: dev
