name: Run Every 5 Minutes

on:
  workflow_dispatch:
  schedule:
    # This cron expression runs the workflow every hour
    - cron: '*/6 * * * *'

jobs:
  run-scheduled-task:
    runs-on: ubuntu-latest
    steps:
      - name: Run a sample script
        run: echo "This workflow runs every hour"
