name: Run Every 5 Minutes

on:
  workflow_dispatch:
  schedule:
    # This cron expression runs the workflow every hour
    - cron: '*/6 * * * *'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: unstable

      - name: Deploy
        uses: ./.github/workflows/example-deploy.yml@example
        with:
          environment: dev
          tag_name: 123456
